version: "2"

services:
    www:
      build:
        context: ./build/www/
        args:
        - APACHE_UID=1000
        - APACHE_GID=1000
      ports: 
      - "62080:80"
      volumes:
      - ./www:/var/www/html/:z
      links:
      - db
      networks:
        vpcbr:
          ipv4_address: 10.5.0.6
    db:
      image: mysql:8.0
      ports: 
      - "62081:3306"
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: remote
        MYSQL_USER: remote
        MYSQL_PASSWORD: 12345
        MYSQL_ROOT_PASSWORD: 12345
      volumes:
      - ./dump:/docker-entrypoint-initdb.d:rw
      - ./conf:/etc/mysql/conf.d:rw
      - persistent:/var/lib/mysql
      networks:
        vpcbr:
          ipv4_address: 10.5.0.5
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
        - db:db
      ports:
        - 62082:80
      environment:
        MYSQL_USER: remote
        MYSQL_PASSWORD: 12345
        MYSQL_ROOT_PASSWORD: 12345 
      networks:
        vpcbr:
          ipv4_address: 10.5.0.4

volumes:
    persistent:

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

